### ISSUE TITLE
 package ‘MixtureModelHMM’ is not available for this version of R

### ISSUE THREAD

**Issue by LiXingguangBrandonStark** [fredjaya/rec-mast#1]
> install.packages("MixtureModelHMM")
Installing package into ‘/Users/lixingguang/Library/R/x86_64/4.1/library’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘MixtureModelHMM’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
>

**Comment by fredjaya** [comment]
The package is not on CRAN, please refer to the [installation instructions for MixtureModelHMM](https://github.com/roblanf/MixtureModelHMM#installation)

**Comment by LiXingguangBrandonStark** [comment]
thanks.

**Comment by LiXingguangBrandonStark** [comment]
could you please tell me how many SARS-CoV-2 sequences can it handle?
