### ISSUE TITLE
Speed up program

### ISSUE THREAD

**Issue by fredjaya** [fredjaya/rec-mast#15]
Ideas to make the program finish faster.  

Currently, only a single instance of either `split_aln()` or `mast()` processes are run at once. Slow, but easy to control resource usage and debugging. IQ-TREE threads can be defined through python CLI with `-T`.

- [ ] Use `multiprocessing.pool`
- [ ] Continue iterations with the best performing model (will only work when discarding duplicate topologies #14)

~~-Benchmark the use of `-T AUTO` vs. arbitrary number  i.e. `-T 8`~~
- https://github.com/fredjaya/rec-mast/issues/15#issuecomment-1425049078

~~Depending on infrastructure, change `--num_threads` to be `--total_threads` across all processes~~
~~Same with memory usage~~
- Just use `mp.pool` but perhaps add flag, so it only runs on a cluster

**Comment by roblanf** [comment]
@fredjaya definitely don't use -T AUTO.

Your datasets for simulations will have fairly predictable sizes, and -T AUTO is usually pretty slow. A smallish number like 2, 4, or 8 is usually best...
